/** Greater Manchester borough structure — maps each live location page to its
 * metropolitan borough, matching the council/postal-area groupings used by
 * the business's own service-area coverage. Only pages that actually exist
 * on the site are listed here. */

export interface LocationArea {
  name: string
  slug: string
}

export interface Borough {
  name: string
  /** Slug of the borough's own page, or null if there isn't a dedicated borough page. */
  slug: string | null
  towns: LocationArea[]
}

export const BOROUGHS: Borough[] = [
  {
    name: 'Bury',
    slug: 'bury',
    towns: [
      { name: 'Prestwich', slug: 'prestwich' },
      { name: 'Radcliffe', slug: 'radcliffe' },
      { name: 'Ramsbottom', slug: 'ramsbottom' },
      { name: 'Tottington', slug: 'tottington' },
      { name: 'Whitefield', slug: 'whitefield' },
      { name: 'Affetside', slug: 'affetside' },
      { name: 'Ainsworth', slug: 'ainsworth' },
      { name: 'Birtle', slug: 'birtle' },
      { name: 'Edenfield', slug: 'edenfield' },
      { name: 'Fishpool', slug: 'fishpool' },
      { name: 'Greenmount', slug: 'greenmount' },
      { name: 'Heap Bridge', slug: 'heap-bridge' },
      { name: 'Holcombe', slug: 'holcombe' },
      { name: 'Simister', slug: 'simister' },
      { name: 'Summerseat', slug: 'summerseat' },
      { name: 'Unsworth', slug: 'unsworth' },
    ],
  },
  {
    name: 'Bolton',
    slug: 'bolton',
    towns: [
      { name: 'Blackrod', slug: 'blackrod' },
      { name: 'Farnworth', slug: 'farnworth' },
      { name: 'Horwich', slug: 'horwich' },
      { name: 'Kearsley', slug: 'kearsley' },
      { name: 'Little Lever', slug: 'little-lever' },
      { name: 'South Turton', slug: 'south-turton' },
      { name: 'Westhoughton', slug: 'westhoughton' },
      { name: 'Astley Bridge', slug: 'astley-bridge' },
      { name: 'Breightmet', slug: 'breightmet' },
      { name: 'Bromley Cross', slug: 'bromley-cross' },
      { name: 'Deane', slug: 'deane' },
      { name: 'Eagley', slug: 'eagley' },
      { name: 'Great Lever', slug: 'great-lever' },
      { name: "Hall i' th' Wood", slug: 'hall-i-th-wood' },
      { name: 'Harwood', slug: 'harwood' },
      { name: 'Lostock', slug: 'lostock' },
      { name: 'Smithills', slug: 'smithills' },
      { name: 'Tonge Moor', slug: 'tonge-moor' },
    ],
  },
  {
    name: 'Manchester',
    slug: 'manchester',
    towns: [
      { name: 'Blackley', slug: 'blackley' },
      { name: 'Cheetham Hill', slug: 'cheetham-hill' },
      { name: 'Chorlton-cum-Hardy', slug: 'chorlton-cum-hardy' },
      { name: 'Didsbury', slug: 'didsbury' },
      { name: 'Beswick', slug: 'beswick' },
      { name: 'Fallowfield', slug: 'fallowfield' },
      { name: 'Hulme', slug: 'hulme' },
      { name: 'Moss Side', slug: 'moss-side' },
      { name: 'Newton Heath', slug: 'newton-heath' },
      { name: 'Northenden', slug: 'northenden' },
      { name: 'Ringway', slug: 'ringway' },
      { name: 'Rusholme', slug: 'rusholme' },
      { name: 'Withington', slug: 'withington' },
      { name: 'Wythenshawe', slug: 'wythenshawe' },
      { name: 'Longsight', slug: 'longsight' },
      { name: 'Ancoats', slug: 'ancoats' },
      { name: 'Ardwick', slug: 'ardwick' },
      { name: 'Burnage', slug: 'burnage' },
      { name: 'Clayton', slug: 'clayton' },
      { name: 'Collyhurst', slug: 'collyhurst' },
      { name: 'Firswood', slug: 'firswood' },
      { name: 'Gorton', slug: 'gorton' },
      { name: 'Harpurhey', slug: 'harpurhey' },
      { name: 'Ladybarn', slug: 'ladybarn' },
      { name: 'Levenshulme', slug: 'levenshulme' },
      { name: 'Mancunian Way area', slug: 'mancunian-way-area' },
      { name: 'Miles Platting', slug: 'miles-platting' },
      { name: 'Moston', slug: 'moston' },
      { name: 'Openshaw', slug: 'openshaw' },
      { name: 'Whalley Range', slug: 'whalley-range' },
    ],
  },
  {
    name: 'Oldham',
    slug: 'oldham',
    towns: [
      { name: 'Chadderton', slug: 'chadderton' },
      { name: 'Failsworth', slug: 'failsworth' },
      { name: 'Lees', slug: 'lees' },
      { name: 'Royton', slug: 'royton' },
      { name: 'Saddleworth', slug: 'saddleworth' },
      { name: 'Shaw and Crompton', slug: 'shaw-and-crompton' },
      { name: 'Hollinwood', slug: 'hollinwood' },
      { name: 'Uppermill', slug: 'uppermill' },
      { name: 'Austerlands', slug: 'austerlands' },
      { name: 'Delph', slug: 'delph' },
      { name: 'Denshaw', slug: 'denshaw' },
      { name: 'Derker', slug: 'derker' },
      { name: 'Diggle', slug: 'diggle' },
      { name: 'Dobcross', slug: 'dobcross' },
      { name: 'Failsworth Pole', slug: 'failsworth-pole' },
      { name: 'Fitton Hill', slug: 'fitton-hill' },
      { name: 'Glodwick', slug: 'glodwick' },
      { name: 'Grasscroft', slug: 'grasscroft' },
      { name: 'Hathershaw', slug: 'hathershaw' },
      { name: 'Lydgate', slug: 'lydgate' },
      { name: 'Scouthead', slug: 'scouthead' },
      { name: 'Springhead', slug: 'springhead' },
      { name: 'Waterhead', slug: 'waterhead' },
      { name: 'Werneth', slug: 'werneth' },
    ],
  },
  {
    name: 'Rochdale',
    slug: 'rochdale',
    towns: [
      { name: 'Heywood', slug: 'heywood' },
      { name: 'Littleborough', slug: 'littleborough' },
      { name: 'Middleton', slug: 'middleton' },
      { name: 'Milnrow', slug: 'milnrow' },
      { name: 'Newhey', slug: 'newhey' },
      { name: 'Wardle', slug: 'wardle' },
      { name: 'Castleton', slug: 'castleton' },
      { name: 'Whitworth', slug: 'whitworth' },
      { name: 'Bamford', slug: 'bamford' },
      { name: 'Belfield', slug: 'belfield' },
      { name: 'Crown Oil area/Heywood', slug: 'crown-oil-area-heywood' },
      { name: 'Dearnley', slug: 'dearnley' },
      { name: 'Healey', slug: 'healey' },
      { name: 'Hurstead', slug: 'hurstead' },
      { name: 'Kirkholt', slug: 'kirkholt' },
      { name: 'Norden', slug: 'norden' },
      { name: 'Shawclough', slug: 'shawclough' },
      { name: 'Smallbridge', slug: 'smallbridge' },
      { name: 'Summit', slug: 'summit' },
      { name: 'Syke', slug: 'syke' },
      { name: 'Thrum Hall', slug: 'thrum-hall' },
    ],
  },
  {
    name: 'Salford',
    slug: 'salford',
    towns: [
      { name: 'Cadishead', slug: 'cadishead' },
      { name: 'Eccles', slug: 'eccles' },
      { name: 'Greengate', slug: 'greengate' },
      { name: 'Pendlebury', slug: 'pendlebury' },
      { name: 'Pendleton', slug: 'pendleton' },
      { name: 'Swinton', slug: 'swinton' },
      { name: 'Walkden', slug: 'walkden' },
      { name: 'Worsley', slug: 'worsley' },
      { name: 'Irlam', slug: 'irlam' },
      { name: 'Little Hulton', slug: 'little-hulton' },
      { name: 'Agecroft', slug: 'agecroft' },
      { name: 'Broughton', slug: 'broughton' },
      { name: 'Clifton', slug: 'clifton' },
      { name: 'Higher Broughton', slug: 'higher-broughton' },
      { name: "Irlam o' th' Height", slug: 'irlam-o-th-height' },
      { name: 'Kersal', slug: 'kersal' },
      { name: 'Lower Broughton', slug: 'lower-broughton' },
      { name: 'MediaCityUK', slug: 'mediacityuk' },
      { name: 'Monton', slug: 'monton' },
      { name: 'Ordsall', slug: 'ordsall' },
      { name: 'Patricroft', slug: 'patricroft' },
      { name: 'Salford Quays', slug: 'salford-quays' },
      { name: 'Swinton Park', slug: 'swinton-park' },
      { name: 'Weaste', slug: 'weaste' },
      { name: 'Winton', slug: 'winton' },
    ],
  },
  {
    name: 'Stockport',
    slug: 'stockport',
    towns: [
      { name: 'Bramhall', slug: 'bramhall' },
      { name: 'Bredbury', slug: 'bredbury' },
      { name: 'Cheadle', slug: 'cheadle' },
      { name: 'Gatley', slug: 'gatley' },
      { name: 'Hazel Grove', slug: 'hazel-grove' },
      { name: 'Heaton Chapel', slug: 'heaton-chapel' },
      { name: 'Heaton Mersey', slug: 'heaton-mersey' },
      { name: 'Heaton Moor', slug: 'heaton-moor' },
      { name: 'Heaton Norris', slug: 'heaton-norris' },
      { name: 'Marple', slug: 'marple' },
      { name: 'Marple Bridge', slug: 'marple-bridge' },
      { name: 'Mellor', slug: 'mellor' },
      { name: 'Reddish', slug: 'reddish' },
      { name: 'Romiley', slug: 'romiley' },
      { name: 'Cheadle Hulme', slug: 'cheadle-hulme' },
      { name: 'Heald Green', slug: 'heald-green' },
      { name: 'High Lane', slug: 'high-lane' },
      { name: 'Woodley', slug: 'woodley' },
      { name: 'Adswood', slug: 'adswood' },
      { name: 'Bosden', slug: 'bosden' },
      { name: 'Brinnington', slug: 'brinnington' },
      { name: 'Compstall', slug: 'compstall' },
      { name: 'Davenport', slug: 'davenport' },
      { name: 'Disley', slug: 'disley' },
      { name: 'Edgeley', slug: 'edgeley' },
      { name: 'Great Moor', slug: 'great-moor' },
      { name: 'Offerton', slug: 'offerton' },
    ],
  },
  {
    name: 'Tameside',
    slug: 'tameside',
    towns: [
      { name: 'Ashton-under-Lyne', slug: 'ashton-under-lyne' },
      { name: 'Audenshaw', slug: 'audenshaw' },
      { name: 'Broadbottom', slug: 'broadbottom' },
      { name: 'Denton', slug: 'denton' },
      { name: 'Droylsden', slug: 'droylsden' },
      { name: 'Dukinfield', slug: 'dukinfield' },
      { name: 'Hattersley', slug: 'hattersley' },
      { name: 'Hollingworth', slug: 'hollingworth' },
      { name: 'Hyde', slug: 'hyde' },
      { name: 'Longdendale', slug: 'longdendale' },
      { name: 'Mossley', slug: 'mossley' },
      { name: 'Mottram-in-Longdendale', slug: 'mottram-in-longdendale' },
      { name: 'Stalybridge', slug: 'stalybridge' },
      { name: 'Flowery Field', slug: 'flowery-field' },
      { name: 'Gee Cross', slug: 'gee-cross' },
      { name: 'Guide Bridge', slug: 'guide-bridge' },
      { name: 'Hartshead', slug: 'hartshead' },
      { name: 'Hurst', slug: 'hurst' },
      { name: 'Lumb Lane', slug: 'lumb-lane' },
      { name: 'Millbrook', slug: 'millbrook' },
      { name: 'Newton', slug: 'newton' },
      { name: 'Stalyhill', slug: 'stalyhill' },
    ],
  },
  {
    name: 'Trafford',
    slug: 'trafford',
    towns: [
      { name: 'Stretford', slug: 'stretford' },
      { name: 'Altrincham', slug: 'altrincham' },
      { name: 'Bowdon', slug: 'bowdon' },
      { name: 'Hale', slug: 'hale' },
      { name: 'Old Trafford', slug: 'old-trafford' },
      { name: 'Sale', slug: 'sale' },
      { name: 'Timperley', slug: 'timperley' },
      { name: 'Urmston', slug: 'urmston' },
      { name: 'Ashton upon Mersey', slug: 'ashton-upon-mersey' },
      { name: 'Davyhulme', slug: 'davyhulme' },
      { name: 'Flixton', slug: 'flixton' },
      { name: 'Partington', slug: 'partington' },
      { name: 'Baguley', slug: 'baguley' },
      { name: 'Broadheath', slug: 'broadheath' },
      { name: 'Brooklands', slug: 'brooklands' },
      { name: 'Carrington', slug: 'carrington' },
      { name: 'Dunham Massey', slug: 'dunham-massey' },
      { name: 'Priory Green', slug: 'priory-green' },
      { name: 'Sale Moor', slug: 'sale-moor' },
      { name: 'Urmston Meadows', slug: 'urmston-meadows' },
    ],
  },
  {
    name: 'Wigan',
    slug: 'wigan',
    towns: [
      { name: 'Abram', slug: 'abram' },
      { name: 'Ashton-in-Makerfield', slug: 'ashton-in-makerfield' },
      { name: 'Aspull', slug: 'aspull' },
      { name: 'Astley', slug: 'astley' },
      { name: 'Atherton', slug: 'atherton' },
      { name: 'Bryn', slug: 'bryn' },
      { name: 'Golborne', slug: 'golborne' },
      { name: 'Higher End', slug: 'higher-end' },
      { name: 'Hindley', slug: 'hindley' },
      { name: 'Ince-in-Makerfield', slug: 'ince-in-makerfield' },
      { name: 'Leigh', slug: 'leigh' },
      { name: 'Orrell', slug: 'orrell' },
      { name: 'Shevington', slug: 'shevington' },
      { name: 'Standish', slug: 'standish' },
      { name: 'Tyldesley', slug: 'tyldesley' },
      { name: 'Winstanley', slug: 'winstanley' },
      { name: 'Billinge', slug: 'billinge' },
      { name: 'Hindley Green', slug: 'hindley-green' },
      { name: 'Lowton', slug: 'lowton' },
      { name: 'Pemberton', slug: 'pemberton' },
      { name: 'Bickershaw', slug: 'bickershaw' },
      { name: 'Haigh', slug: 'haigh' },
      { name: 'Newtown', slug: 'newtown' },
      { name: 'Platt Bridge', slug: 'platt-bridge' },
      { name: 'Scholes', slug: 'scholes' },
      { name: 'Spring View', slug: 'spring-view' },
      { name: 'Worthington', slug: 'worthington' },
    ],
  },
]

/** Every area (borough page + town page) in one flat list, each tagged with its borough name. */
export const ALL_AREAS: (LocationArea & { borough: string })[] = BOROUGHS.flatMap((b) => [
  ...(b.slug ? [{ name: b.name, slug: b.slug, borough: b.name }] : []),
  ...b.towns.map((t) => ({ ...t, borough: b.name })),
])

/** Finds the borough that a given page slug belongs to. */
export function findBorough(slug: string): Borough | undefined {
  return BOROUGHS.find((b) => b.slug === slug || b.towns.some((t) => t.slug === slug))
}

/** Returns the other areas in the same borough as `slug` (borough page + sibling towns), excluding `slug` itself. */
export function nearbyAreas(slug: string): LocationArea[] {
  const borough = findBorough(slug)
  if (!borough) return []
  const all: LocationArea[] = [
    ...(borough.slug ? [{ name: borough.name, slug: borough.slug }] : []),
    ...borough.towns,
  ]
  return all.filter((a) => a.slug !== slug)
}
